# Generated by Django 5.1.5 on 2025-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.TextField(blank=True, default=''),
        ),
    ]
