# Generated by Django 5.1.5 on 2025-02-02 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_language_alter_faq_question_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
